"""Tree-sitter node type strings used in PHP frontend lowerers.

Centralises raw string literals so that typos are caught at import time
and grep/refactor is trivial.
"""


class PHPNodeType:
    """Tree-sitter node type strings used in PHP frontend lowerers."""

    # -- Literals & atoms --------------------------------------------------
    VARIABLE_NAME = "variable_name"
    NAME = "name"
    INTEGER = "integer"
    FLOAT = "float"
    STRING = "string"
    ENCAPSED_STRING = "encapsed_string"
    BOOLEAN = "boolean"
    NULL = "null"
    HEREDOC = "heredoc"
    HEREDOC_BODY = "heredoc_body"
    NOWDOC = "nowdoc"
    RELATIVE_SCOPE = "relative_scope"
    STRING_CONTENT = "string_content"
    ESCAPE_SEQUENCE = "escape_sequence"

    # -- Expressions -------------------------------------------------------
    BINARY_EXPRESSION = "binary_expression"
    UNARY_OP_EXPRESSION = "unary_op_expression"
    UPDATE_EXPRESSION = "update_expression"
    FUNCTION_CALL_EXPRESSION = "function_call_expression"
    MEMBER_CALL_EXPRESSION = "member_call_expression"
    MEMBER_ACCESS_EXPRESSION = "member_access_expression"
    SUBSCRIPT_EXPRESSION = "subscript_expression"
    PARENTHESIZED_EXPRESSION = "parenthesized_expression"
    ARRAY_CREATION_EXPRESSION = "array_creation_expression"
    ASSIGNMENT_EXPRESSION = "assignment_expression"
    AUGMENTED_ASSIGNMENT_EXPRESSION = "augmented_assignment_expression"
    CAST_EXPRESSION = "cast_expression"
    CONDITIONAL_EXPRESSION = "conditional_expression"
    THROW_EXPRESSION = "throw_expression"
    OBJECT_CREATION_EXPRESSION = "object_creation_expression"
    MATCH_EXPRESSION = "match_expression"
    ARROW_FUNCTION = "arrow_function"
    SCOPED_CALL_EXPRESSION = "scoped_call_expression"
    ANONYMOUS_FUNCTION = "anonymous_function"
    NULLSAFE_MEMBER_ACCESS_EXPRESSION = "nullsafe_member_access_expression"
    CLASS_CONSTANT_ACCESS_EXPRESSION = "class_constant_access_expression"
    SCOPED_PROPERTY_ACCESS_EXPRESSION = "scoped_property_access_expression"
    YIELD_EXPRESSION = "yield_expression"
    REFERENCE_ASSIGNMENT_EXPRESSION = "reference_assignment_expression"
    DYNAMIC_VARIABLE_NAME = "dynamic_variable_name"
    INCLUDE_EXPRESSION = "include_expression"
    NULLSAFE_MEMBER_CALL_EXPRESSION = "nullsafe_member_call_expression"
    REQUIRE_ONCE_EXPRESSION = "require_once_expression"
    VARIADIC_UNPACKING = "variadic_unpacking"
    PRINT_INTRINSIC = "print_intrinsic"
    CLONE_EXPRESSION = "clone_expression"
    LIST_LITERAL = "list_literal"
    ANONYMOUS_CLASS = "anonymous_class"
    ERROR_SUPPRESSION_EXPRESSION = "error_suppression_expression"
    SEQUENCE_EXPRESSION = "sequence_expression"
    INCLUDE_ONCE_EXPRESSION = "include_once_expression"
    REQUIRE_EXPRESSION = "require_expression"

    # -- Statements --------------------------------------------------------
    EXPRESSION_STATEMENT = "expression_statement"
    RETURN_STATEMENT = "return_statement"
    ECHO_STATEMENT = "echo_statement"
    IF_STATEMENT = "if_statement"
    WHILE_STATEMENT = "while_statement"
    FOR_STATEMENT = "for_statement"
    FOREACH_STATEMENT = "foreach_statement"
    FUNCTION_DEFINITION = "function_definition"
    METHOD_DECLARATION = "method_declaration"
    BASE_CLAUSE = "base_clause"
    CLASS_DECLARATION = "class_declaration"
    COMPOUND_STATEMENT = "compound_statement"
    PROGRAM = "program"
    BREAK_STATEMENT = "break_statement"
    CONTINUE_STATEMENT = "continue_statement"
    TRY_STATEMENT = "try_statement"
    SWITCH_STATEMENT = "switch_statement"
    DO_STATEMENT = "do_statement"
    NAMESPACE_DEFINITION = "namespace_definition"
    INTERFACE_DECLARATION = "interface_declaration"
    TRAIT_DECLARATION = "trait_declaration"
    FUNCTION_STATIC_DECLARATION = "function_static_declaration"
    ENUM_DECLARATION = "enum_declaration"
    NAMED_LABEL_STATEMENT = "named_label_statement"
    GOTO_STATEMENT = "goto_statement"
    PROPERTY_DECLARATION = "property_declaration"
    USE_DECLARATION = "use_declaration"
    NAMESPACE_USE_DECLARATION = "namespace_use_declaration"
    ENUM_CASE = "enum_case"
    GLOBAL_DECLARATION = "global_declaration"
    CONST_DECLARATION = "const_declaration"
    EXIT_STATEMENT = "exit_statement"
    DECLARE_STATEMENT = "declare_statement"
    UNSET_STATEMENT = "unset_statement"

    # -- Const element nodes -----------------------------------------------
    CONST_ELEMENT = "const_element"

    # -- Control-flow clause types -----------------------------------------
    ELSE_CLAUSE = "else_clause"
    ELSE_IF_CLAUSE = "else_if_clause"
    CATCH_CLAUSE = "catch_clause"
    FINALLY_CLAUSE = "finally_clause"
    CASE_STATEMENT = "case_statement"
    DEFAULT_STATEMENT = "default_statement"
    MATCH_CONDITIONAL_EXPRESSION = "match_conditional_expression"
    MATCH_DEFAULT_EXPRESSION = "match_default_expression"

    # -- Parameter & type nodes --------------------------------------------
    SIMPLE_PARAMETER = "simple_parameter"
    VARIADIC_PARAMETER = "variadic_parameter"
    NAMED_TYPE = "named_type"
    QUALIFIED_NAME = "qualified_name"
    ARGUMENTS = "arguments"
    ARRAY_ELEMENT_INITIALIZER = "array_element_initializer"
    PAIR = "pair"
    PROPERTY_ELEMENT = "property_element"
    STATIC_VARIABLE_DECLARATION = "static_variable_declaration"
    STATIC_MODIFIER = "static_modifier"
    DECLARATION_LIST = "declaration_list"

    # -- Comment / noise ---------------------------------------------------
    COMMENT = "comment"
    PHP_TAG = "php_tag"
    TEXT_INTERPOLATION = "text_interpolation"
    PHP_END_TAG = "php_end_tag"
    NEWLINE = "\n"

    # -- Modifier nodes ----------------------------------------------------
    VISIBILITY_MODIFIER = "visibility_modifier"
    ABSTRACT_MODIFIER = "abstract_modifier"
    FINAL_MODIFIER = "final_modifier"

    # -- Keywords (appear as node types) -----------------------------------
    RETURN = "return"
    ECHO = "echo"
    ELSE = "else"

    # -- Punctuation tokens ------------------------------------------------
    OPEN_BRACE = "{"
    CLOSE_BRACE = "}"
    OPEN_PAREN = "("
    CLOSE_PAREN = ")"
    COMMA = ","
