"""Tree-sitter node type constants for the Rust frontend."""


class RustNodeType:
    """All tree-sitter Rust node type strings used throughout the Rust frontend."""

    # ── Identifiers & names ──────────────────────────────────────────
    IDENTIFIER = "identifier"
    TYPE_IDENTIFIER = "type_identifier"
    SELF = "self"
    SCOPED_IDENTIFIER = "scoped_identifier"
    SCOPED_TYPE_IDENTIFIER = "scoped_type_identifier"
    FIELD_IDENTIFIER = "field_identifier"
    SHORTHAND_FIELD_IDENTIFIER = "shorthand_field_identifier"

    # ── Literals ─────────────────────────────────────────────────────
    INTEGER_LITERAL = "integer_literal"
    FLOAT_LITERAL = "float_literal"
    STRING_LITERAL = "string_literal"
    CHAR_LITERAL = "char_literal"
    BOOLEAN_LITERAL = "boolean_literal"
    RAW_STRING_LITERAL = "raw_string_literal"
    STRING_CONTENT = "string_content"
    NEGATIVE_LITERAL = "negative_literal"
    TRUE = "true"
    FALSE = "false"
    UNIT_EXPRESSION = "unit_expression"

    # ── Expressions ──────────────────────────────────────────────────
    BINARY_EXPRESSION = "binary_expression"
    UNARY_EXPRESSION = "unary_expression"
    PARENTHESIZED_EXPRESSION = "parenthesized_expression"
    CALL_EXPRESSION = "call_expression"
    FIELD_EXPRESSION = "field_expression"
    REFERENCE_EXPRESSION = "reference_expression"
    DEREFERENCE_EXPRESSION = "dereference_expression"
    ASSIGNMENT_EXPRESSION = "assignment_expression"
    COMPOUND_ASSIGNMENT_EXPR = "compound_assignment_expr"
    IF_EXPRESSION = "if_expression"
    MATCH_EXPRESSION = "match_expression"
    CLOSURE_EXPRESSION = "closure_expression"
    STRUCT_EXPRESSION = "struct_expression"
    RETURN_EXPRESSION = "return_expression"
    MACRO_INVOCATION = "macro_invocation"
    ARRAY_EXPRESSION = "array_expression"
    INDEX_EXPRESSION = "index_expression"
    TUPLE_EXPRESSION = "tuple_expression"
    RANGE_EXPRESSION = "range_expression"
    TRY_EXPRESSION = "try_expression"
    AWAIT_EXPRESSION = "await_expression"
    TYPE_CAST_EXPRESSION = "type_cast_expression"
    EXPRESSION_STATEMENT = "expression_statement"
    WHILE_EXPRESSION = "while_expression"
    LOOP_EXPRESSION = "loop_expression"
    FOR_EXPRESSION = "for_expression"
    CONTINUE_EXPRESSION = "continue_expression"
    BREAK_EXPRESSION = "break_expression"
    GENERIC_FUNCTION = "generic_function"
    LET_CONDITION = "let_condition"
    LET_CHAIN = "let_chain"

    # ── Declarations / items ─────────────────────────────────────────
    FUNCTION_ITEM = "function_item"
    FUNCTION_SIGNATURE_ITEM = "function_signature_item"
    STRUCT_ITEM = "struct_item"
    IMPL_ITEM = "impl_item"
    TRAIT_ITEM = "trait_item"
    ENUM_ITEM = "enum_item"
    CONST_ITEM = "const_item"
    STATIC_ITEM = "static_item"
    TYPE_ITEM = "type_item"
    MOD_ITEM = "mod_item"
    LET_DECLARATION = "let_declaration"
    USE_DECLARATION = "use_declaration"
    EXTERN_CRATE_DECLARATION = "extern_crate_declaration"
    ATTRIBUTE_ITEM = "attribute_item"
    FOREIGN_MOD_ITEM = "foreign_mod_item"
    UNION_ITEM = "union_item"
    MACRO_DEFINITION = "macro_definition"

    # ── Patterns ─────────────────────────────────────────────────────
    MATCH_ARM = "match_arm"
    MATCH_PATTERN = "match_pattern"
    TUPLE_PATTERN = "tuple_pattern"
    STRUCT_PATTERN = "struct_pattern"
    TUPLE_STRUCT_PATTERN = "tuple_struct_pattern"
    FIELD_PATTERN = "field_pattern"
    OR_PATTERN = "or_pattern"
    MUT_PATTERN = "mut_pattern"
    REFERENCE_PATTERN = "reference_pattern"
    SLICE_PATTERN = "slice_pattern"
    REMAINING_FIELD_PATTERN = "remaining_field_pattern"
    CAPTURED_PATTERN = "captured_pattern"

    # ── Parameters ───────────────────────────────────────────────────
    PARAMETER = "parameter"
    SELF_PARAMETER = "self_parameter"
    MUTABLE_SPECIFIER = "mutable_specifier"

    # ── Blocks / structural ──────────────────────────────────────────
    BLOCK = "block"
    SOURCE_FILE = "source_file"
    ELSE_CLAUSE = "else_clause"
    ASYNC_BLOCK = "async_block"
    UNSAFE_BLOCK = "unsafe_block"
    FIELD_INITIALIZER = "field_initializer"

    # ── Comments ─────────────────────────────────────────────────────
    COMMENT = "comment"
    LINE_COMMENT = "line_comment"
    BLOCK_COMMENT = "block_comment"

    # ── Punctuation / keywords (used in child-type filtering) ────────
    OPEN_PAREN = "("
    CLOSE_PAREN = ")"
    OPEN_BRACE = "{"
    CLOSE_BRACE = "}"
    COMMA = ","
    COLON = ":"
    SEMICOLON = ";"
    ARROW = "->"
    FAT_ARROW = "=>"
    AMPERSAND = "&"
    ASTERISK = "*"
    QUESTION_MARK = "?"
    DOT = "."
    PIPE = "|"
    RETURN_KEYWORD = "return"
    MUT_KEYWORD = "mut"
    AWAIT_KEYWORD = "await"
    FAT_ARROW_ALIAS = "fat_arrow"
    NEWLINE = "\n"
