"""C tree-sitter node type constants."""


class CNodeType:
    """Constants for C tree-sitter node type strings."""

    # Literals and identifiers
    IDENTIFIER = "identifier"
    TYPE_IDENTIFIER = "type_identifier"
    NUMBER_LITERAL = "number_literal"
    STRING_LITERAL = "string_literal"
    CHAR_LITERAL = "char_literal"
    TRUE = "true"
    FALSE = "false"
    NULL = "null"
    CONCATENATED_STRING = "concatenated_string"

    # Expressions
    BINARY_EXPRESSION = "binary_expression"
    UNARY_EXPRESSION = "unary_expression"
    UPDATE_EXPRESSION = "update_expression"
    PARENTHESIZED_EXPRESSION = "parenthesized_expression"
    CALL_EXPRESSION = "call_expression"
    FIELD_EXPRESSION = "field_expression"
    SUBSCRIPT_EXPRESSION = "subscript_expression"
    ASSIGNMENT_EXPRESSION = "assignment_expression"
    CAST_EXPRESSION = "cast_expression"
    POINTER_EXPRESSION = "pointer_expression"
    SIZEOF_EXPRESSION = "sizeof_expression"
    CONDITIONAL_EXPRESSION = "conditional_expression"
    COMMA_EXPRESSION = "comma_expression"
    COMPOUND_LITERAL_EXPRESSION = "compound_literal_expression"

    # Statements
    EXPRESSION_STATEMENT = "expression_statement"
    RETURN_STATEMENT = "return_statement"
    IF_STATEMENT = "if_statement"
    WHILE_STATEMENT = "while_statement"
    FOR_STATEMENT = "for_statement"
    DO_STATEMENT = "do_statement"
    SWITCH_STATEMENT = "switch_statement"
    CASE_STATEMENT = "case_statement"
    GOTO_STATEMENT = "goto_statement"
    LABELED_STATEMENT = "labeled_statement"
    BREAK_STATEMENT = "break_statement"
    CONTINUE_STATEMENT = "continue_statement"
    COMPOUND_STATEMENT = "compound_statement"
    STATEMENT_IDENTIFIER = "statement_identifier"

    # Declarations
    DECLARATION = "declaration"
    INIT_DECLARATOR = "init_declarator"
    FUNCTION_DEFINITION = "function_definition"
    FUNCTION_DECLARATOR = "function_declarator"
    PARAMETER_DECLARATION = "parameter_declaration"
    TYPE_DEFINITION = "type_definition"
    STRUCT_SPECIFIER = "struct_specifier"
    ENUM_SPECIFIER = "enum_specifier"
    UNION_SPECIFIER = "union_specifier"
    FIELD_DECLARATION = "field_declaration"
    FIELD_IDENTIFIER = "field_identifier"
    ENUMERATOR = "enumerator"
    TYPE_DESCRIPTOR = "type_descriptor"
    PARENTHESIZED_DECLARATOR = "parenthesized_declarator"
    POINTER_DECLARATOR = "pointer_declarator"
    FIELD_DESIGNATOR = "field_designator"
    INITIALIZER_LIST = "initializer_list"
    INITIALIZER_PAIR = "initializer_pair"

    # Preprocessor
    PREPROC_INCLUDE = "preproc_include"
    PREPROC_DEFINE = "preproc_define"
    PREPROC_IFDEF = "preproc_ifdef"
    PREPROC_IFNDEF = "preproc_ifndef"
    PREPROC_IF = "preproc_if"
    PREPROC_ELSE = "preproc_else"
    PREPROC_ELIF = "preproc_elif"
    PREPROC_ENDIF = "preproc_endif"
    PREPROC_CALL = "preproc_call"
    PREPROC_DEF = "preproc_def"
    PREPROC_FUNCTION_DEF = "preproc_function_def"
    PREPROC_ARG = "preproc_arg"

    # Other
    COMMENT = "comment"
    TRANSLATION_UNIT = "translation_unit"
    SIZEOF = "sizeof"
    CASE = "case"
    DEFAULT = "default"
