"""C# tree-sitter node type constants."""


class CSharpNodeType:
    """Constants for C# tree-sitter node type strings."""

    # -- Literals & atoms --
    IDENTIFIER = "identifier"
    INTEGER_LITERAL = "integer_literal"
    REAL_LITERAL = "real_literal"
    STRING_LITERAL = "string_literal"
    CHARACTER_LITERAL = "character_literal"
    VERBATIM_STRING_LITERAL = "verbatim_string_literal"
    BOOLEAN_LITERAL = "boolean_literal"
    NULL_LITERAL = "null_literal"
    STRING_CONTENT = "string_content"
    COMMENT = "comment"
    PREDEFINED_TYPE = "predefined_type"
    TYPE_IDENTIFIER = "type_identifier"
    ARRAY_TYPE = "array_type"
    DISCARD = "discard"

    # -- Expressions --
    BINARY_EXPRESSION = "binary_expression"
    PREFIX_UNARY_EXPRESSION = "prefix_unary_expression"
    POSTFIX_UNARY_EXPRESSION = "postfix_unary_expression"
    PARENTHESIZED_EXPRESSION = "parenthesized_expression"
    INVOCATION_EXPRESSION = "invocation_expression"
    OBJECT_CREATION_EXPRESSION = "object_creation_expression"
    MEMBER_ACCESS_EXPRESSION = "member_access_expression"
    ELEMENT_ACCESS_EXPRESSION = "element_access_expression"
    INITIALIZER_EXPRESSION = "initializer_expression"
    ASSIGNMENT_EXPRESSION = "assignment_expression"
    CAST_EXPRESSION = "cast_expression"
    CONDITIONAL_EXPRESSION = "conditional_expression"
    INTERPOLATED_STRING_EXPRESSION = "interpolated_string_expression"
    TYPEOF_EXPRESSION = "typeof_expression"
    DEFAULT_EXPRESSION = "default_expression"
    SIZEOF_EXPRESSION = "sizeof_expression"
    CHECKED_EXPRESSION = "checked_expression"
    IS_EXPRESSION = "is_expression"
    AS_EXPRESSION = "as_expression"
    LAMBDA_EXPRESSION = "lambda_expression"
    ARRAY_CREATION_EXPRESSION = "array_creation_expression"
    IMPLICIT_ARRAY_CREATION_EXPRESSION = "implicit_array_creation_expression"
    IMPLICIT_OBJECT_CREATION_EXPRESSION = "implicit_object_creation_expression"
    ANONYMOUS_OBJECT_CREATION_EXPRESSION = "anonymous_object_creation_expression"
    WITH_EXPRESSION = "with_expression"
    WITH_INITIALIZER = "with_initializer"
    QUERY_EXPRESSION = "query_expression"
    AWAIT_EXPRESSION = "await_expression"
    SWITCH_EXPRESSION = "switch_expression"
    CONDITIONAL_ACCESS_EXPRESSION = "conditional_access_expression"
    MEMBER_BINDING_EXPRESSION = "member_binding_expression"
    TUPLE_EXPRESSION = "tuple_expression"
    THIS_EXPRESSION = "this_expression"
    THIS = "this"
    IS_PATTERN_EXPRESSION = "is_pattern_expression"
    CONSTANT_PATTERN = "constant_pattern"
    DECLARATION_PATTERN = "declaration_pattern"
    RECURSIVE_PATTERN = "recursive_pattern"
    PARENTHESIZED_PATTERN = "parenthesized_pattern"
    OR_PATTERN = "or_pattern"
    LIST_PATTERN = "list_pattern"
    RELATIONAL_PATTERN = "relational_pattern"
    AND_PATTERN = "and_pattern"
    NEGATED_PATTERN = "negated_pattern"
    PROPERTY_PATTERN_CLAUSE = "property_pattern_clause"
    SUBPATTERN = "subpattern"
    INTERPOLATION = "interpolation"
    INTERPOLATION_BRACE = "interpolation_brace"
    INTERPOLATION_FORMAT_CLAUSE = "interpolation_format_clause"
    INTERPOLATION_ALIGNMENT_CLAUSE = "interpolation_alignment_clause"
    BRACKETED_ARGUMENT_LIST = "bracketed_argument_list"
    ARGUMENT = "argument"
    TYPEOF = "typeof"

    # -- Statements --
    EXPRESSION_STATEMENT = "expression_statement"
    LOCAL_DECLARATION_STATEMENT = "local_declaration_statement"
    RETURN_STATEMENT = "return_statement"
    IF_STATEMENT = "if_statement"
    WHILE_STATEMENT = "while_statement"
    FOR_STATEMENT = "for_statement"
    FOREACH_STATEMENT = "foreach_statement"
    DO_STATEMENT = "do_statement"
    SWITCH_STATEMENT = "switch_statement"
    THROW_STATEMENT = "throw_statement"
    TRY_STATEMENT = "try_statement"
    BREAK_STATEMENT = "break_statement"
    CONTINUE_STATEMENT = "continue_statement"
    LOCK_STATEMENT = "lock_statement"
    USING_STATEMENT = "using_statement"
    CHECKED_STATEMENT = "checked_statement"
    FIXED_STATEMENT = "fixed_statement"
    YIELD_STATEMENT = "yield_statement"
    EMPTY_STATEMENT = "empty_statement"
    GOTO_STATEMENT = "goto_statement"
    LABELED_STATEMENT = "labeled_statement"
    LABEL_NAME = "label_name"
    THROW_EXPRESSION = "throw_expression"
    RANGE_EXPRESSION = "range_expression"
    GLOBAL_STATEMENT = "global_statement"
    LOCAL_FUNCTION_STATEMENT = "local_function_statement"
    BLOCK = "block"
    ELSE = "else"

    # -- Declarations --
    METHOD_DECLARATION = "method_declaration"
    CONSTRUCTOR_DECLARATION = "constructor_declaration"
    CLASS_DECLARATION = "class_declaration"
    STRUCT_DECLARATION = "struct_declaration"
    INTERFACE_DECLARATION = "interface_declaration"
    ENUM_DECLARATION = "enum_declaration"
    NAMESPACE_DECLARATION = "namespace_declaration"
    FILE_SCOPED_NAMESPACE_DECLARATION = "file_scoped_namespace_declaration"
    FIELD_DECLARATION = "field_declaration"
    PROPERTY_DECLARATION = "property_declaration"
    EVENT_FIELD_DECLARATION = "event_field_declaration"
    EVENT_DECLARATION = "event_declaration"
    RECORD_DECLARATION = "record_declaration"
    RECORD_STRUCT_DECLARATION = "record_struct_declaration"
    VARIABLE_DECLARATION = "variable_declaration"
    VARIABLE_DECLARATOR = "variable_declarator"
    DELEGATE_DECLARATION = "delegate_declaration"
    PARAMETER = "parameter"
    PARAMETER_LIST = "parameter_list"
    MODIFIER = "modifier"
    ATTRIBUTE_LIST = "attribute_list"
    ACCESSOR_LIST = "accessor_list"
    ACCESSOR_DECLARATION = "accessor_declaration"
    ENUM_MEMBER_DECLARATION_LIST = "enum_member_declaration_list"
    ENUM_MEMBER_DECLARATION = "enum_member_declaration"
    CATCH_CLAUSE = "catch_clause"
    CATCH_DECLARATION = "catch_declaration"
    FINALLY_CLAUSE = "finally_clause"
    SWITCH_SECTION = "switch_section"
    SWITCH_EXPRESSION_ARM = "switch_expression_arm"
    QUALIFIED_NAME = "qualified_name"
    GENERIC_NAME = "generic_name"
    DECLARATION_LIST = "declaration_list"
    COMPILATION_UNIT = "compilation_unit"
    BASE_LIST = "base_list"

    # -- Directives / noise --
    USING_DIRECTIVE = "using_directive"
    NEWLINE = "\n"

    # -- Out / ref expressions --
    DECLARATION_EXPRESSION = "declaration_expression"
    IMPLICIT_TYPE = "implicit_type"
    REF_EXPRESSION = "ref_expression"
    REF_TYPE = "ref_type"

    # -- Constructor chaining --
    CONSTRUCTOR_INITIALIZER = "constructor_initializer"
    THIS = "this"
    ARGUMENT_LIST = "argument_list"
    ARGUMENT = "argument"

    # -- Punctuation used in type comparisons --
    LBRACE = "{"
    RBRACE = "}"
    EQUALS_SIGN = "="

    # -- LINQ --
    FROM_CLAUSE = "from_clause"
    SELECT_CLAUSE = "select_clause"
    WHERE_CLAUSE = "where_clause"
